spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      forwarded:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false

      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: TASK-SERVICE
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/tasks/**

        - id: LABEL-SERVICE
          uri: lb://LABEL-SERVICE
          predicates:
            - Path=/api/labels/**

        - id: AUTH-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

  server:
    port: 8080

  main:
    web-application-type: REACTIVE

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
